name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build project using make
      run: |
        chmod +x ./make.sh
        ./make.sh

    - name: Install dependencies
      run: |
        pip install -r tests/requirements.txt

    - name: Run Pytest
      run: |
        pytest --color=yes -v --tb=short --html=pytest_report.html tests

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: pytest_report.html

    # - name: Install clang-format
    #   run: sudo apt-get install -y clang-format

    # - name: Check clang-format
    #   run: |
    #     for file in $(git ls-files 'src/*.c' 'src/*.h'); do
    #       clang-format -n -style=$(pwd)/clang/.clang-format $file
    #     done
  style-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up clang-format
      run: |
        sudo apt-get install -y clang-format

    - name: Check code style with clang-format
      id: clang-format-check
      run: |
        cp clang/.clang-format src/
        if clang-format -n src/*.c src/*.h | tee /dev/tty | (grep -q "warning" && echo "::set-output name=warnings::true" || echo "::set-output name=warnings::false")
        then
          echo "No clang-format warnings found"
        else
          echo "Clang-format warnings found"
        fi

    - name: Set output variable
      if: steps.clang-format-check.outputs.warnings == 'true'
      run: echo "Clang-format warnings found" && echo "::set-output name=exit-code::1" || echo "::set-output name=exit-code::0"

    - name: Fail if clang-format warnings found
      if: steps.clang-format-check.outputs.exit-code == '1'
      run: exit 1
